//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnMyWayCTGV
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class onmywaydbCTGVEntities1 : DbContext
    {
        public onmywaydbCTGVEntities1()
            : base("name=onmywaydbCTGVEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chair> Chair { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Dishe> Dishe { get; set; }
        public virtual DbSet<Table> Table { get; set; }
    }
}
