//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnMyWayCTGV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public Table()
        {
            this.Chair = new HashSet<Chair>();
        }
    
        public int Id { get; set; }
        public int status { get; set; }
        public int x { get; set; }
        public int y { get; set; }
    
        public virtual ICollection<Chair> Chair { get; set; }
    }
}
